# Generated by Django 4.1 on 2022-10-18 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.AddField(
            model_name='article',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
