# Generated by Django 4.1.2 on 2022-10-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Sport', 'Sport'), ('Nature', 'Nature'), ('Travel', 'Travel'), ('Lifestyle', 'Lifestyle'), ('Other', 'Other')], max_length=255),
        ),
    ]
